version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: library-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - library-net

  redis:
    image: redis:7
    container_name: library-redis
    ports:
      - "6380:6379"
    networks:
      - library-net

  app:
    build: .
    container_name: library-app
    depends_on:
      - mysql
      - redis
    ports:
      - "8081:8081"
      - "8443:8443"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - library-net

  frontend:
    build: ../library-fe
    container_name: library-fe
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - library-net

volumes:
  mysql_data:

networks:
  library-net:
    driver: bridge